apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ephemera
  namespace: ephemera
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ephemera.luukblankenstijn.nl`) && PathPrefix(`/`)
      priority: 10
      middlewares:
        - name: authentik-auth
      kind: Rule
      services:
        - name: ephemera
          port: 8286
    - match: Host(`ephemera.luukblankenstijn.nl`) && PathPrefix(`/outpost.goauthentik.io/`)
      priority: 15
      services:
          - kind: Service
            name: authentik-authentik-server
            namespace: authentik
            port: 80
