apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ephemera

resources:
  - ephemera-sealedsecret.yaml
  - deployments.yaml
  - services.yaml
  - ephemera-pvc.yaml
  - ingressRoute.yaml
  - auth-middleware.yaml
