apiVersion: v1
kind: Service
metadata:
  name: ephemera
spec:
  selector:
    app: ephemera
  ports:
    - name: http
      port: 8286
      targetPort: 8286
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
spec:
  selector:
    app: flaresolverr
  ports:
    - name: http
      port: 8191
      targetPort: 8191
