apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infra/sealed-secrets
  - infra/cert-manager
  - infra/flux
  - infra/actions-runner-controller

  - namespaces/sonarqube.yaml
  - apps/sonarqube

  - namespaces/vaultwarden.yaml
  - apps/vaultwarden

  - namespaces/deurmat.yaml
  - apps/deurmat
  
  - namespaces/authentik.yaml
  - apps/authentik
