apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: shelfmark
  namespace: shelfmark
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`shelfmark.luukblankenstijn.nl`) && PathPrefix(`/`)
      priority: 10
      middlewares:
        - name: authentik-auth
      kind: Rule
      services:
        - name: shelfmark
          port: 8084
    - match: Host(`shelfmark.luukblankenstijn.nl`) && PathPrefix(`/outpost.goauthentik.io/`)
      priority: 15
      services:
          - kind: Service
            name: authentik-authentik-server
            namespace: authentik
            port: 80
