apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authentik

resources:
  - helmrelease.yaml
  - authentik-sealedsecret.yaml
  - authentik-postgres-sealedsecret.yaml
  - authentik-email-password-sealedsecret.yaml
