apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authentik

configMapGenerator:
  - name: authentik-values
    namespace: authentik
    files:
      - values.yaml

generatorOptions:
  disableNameSuffixHash: true

resources:
  - helmrelease.yaml
  - cert.yaml
  - authentik-sealedsecret.yaml
  - authentik-postgres-sealedsecret.yaml
