apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: booklore

resources:
  - booklore-sealedSecret.yaml
  - booklore-deploy.yaml
  - booklore-svc.yaml
  - booklore-pvc.yaml
  - mariadb-sealedSecret.yaml
  - mariadb-deploy.yaml
  - mariadb-svc.yaml
  - mariadb-pvc.yaml
  - buffering-middleware.yaml
  - ingressRoute.yaml
