apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    tlsStore:
      default:
        defaultCertificate:
          secretName: wildcard-luukblankenstijn-nl-tls
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
    ports:
      hytale-udp:
        port: 5520
        exposedPort: 5520
        protocol: UDP
        expose:
          default: true
