apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-luukblankenstijn-nl
  namespace: kube-system
spec:
  secretName: wildcard-luukblankenstijn-nl-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns
  dnsNames:
    - luukblankenstijn.nl
    - '*.luukblankenstijn.nl'
