apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: deurmat
resources:
  - cert.yaml
  - pvc.yaml
  - svc.yaml
  - deploy.yaml
  - ingressRoute.yaml
  - authMiddleware.yaml
  - user-secret-sealed.yaml
  - ghcr-pull-sealed.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: deurmat
